application: benny-id-landing-page
version: 1
runtime: php55
api_version: 1
threadsafe: yes

handlers:
- url: /
  static_files: index.html
  upload: index\.html

- url: /(.*\.(png|jpg|ico|css|js|svg|ttf|woff))
  static_files: \1
  upload: (.*\.(png|jpg|ico|css|js|svg|ttf|woff))

- url: /blog
  script: blog.html

- url: /blog(/.*)?
  script: blog/index.php

- url: /.*
  static_files: error.html
  upload: error\.html
